AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This environment is a simple S3 bucket setup to serve a static website
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: {{ environment.inputs.index_document }}
        ErrorDocument: {{ environment.inputs.error_document }}
    DeletionPolicy: Retain

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
            Principal: '*'

Outputs:
  S3BucketNameCommitTest:
    Value: !Ref S3Bucket
  S3BucketName:
    Value: !Ref S3Bucket
  S3BucketArn:
    Value: !GetAtt
      - S3Bucket
      - Arn
  S3WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Secure S3 Bucket URL
  DomainName:
    Value:
      {% if environment.inputs.domain_name %}
        {{ environment.inputs.domain_name }}
      {% else %}
        - !GetAtt
          - S3Bucket
          - DomainName
      {% endif %}
