schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for my static website bucket"
      required:
        - test_input
      properties:
        test_input
          type: string
          description: "Ignore me"
        bucket_name:
          type: string
          description: "A name for your bucket, note that it must be unique across all accounts"
        domain_name:
          type: string
          description: "If you add a domain name we will setup cloudfront for you. Make sure you've registered this domain name with AWS Leave empty if you want to stick with the S3 Urls."
        index_document:
          type: string
          description: "Index document for the static website"
          default: index.html
        error_document:
          type: string
          description: "Error document for the static website"
          default: error.html
