schema:
  format:
    openapi: "3.0.0"
  service_input_type: "WebsiteInputs"
  pipeline_input_type: "PipelineInputs"
  types:
    WebsiteInputs:
      type: object
      description: "Inputs for your static website hosted on S3"
      properties:
        branch_name:
          type: string
          description: "The branch to use for this instance of the website"
        is_prod:
          type: boolean
          description: "Is this prod stage and branch"
          default: false
    PipelineInputs:
      type: object
      description: "Inputs for your static website pipeline"
      properties:
        image:
          type: string
          description: "CodeBuild image to create the build"
          default: "aws/codebuild/standard:5.0"
        install_command:
          type: string
          description: "Install command"
          default: "npm install"
        pre_build_command:
          type: string
          description: "Pre-build command"
          default: "npm run test"
        build_command:
          type: string
          description: "Build command"
          default: "npm run build"
        output_path:
          type: string
          description: "Generated output files to deploy"
          default: "./dist"
        file_match:
          type: string
          description: "File pattern to filter which files to deploy"
          default: "**/*"